version: "3.8"

services:
  postgres:
    image: postgres
    container_name: my_container_db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eligarc
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: my_store
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=postgres
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=postgres
      - PMA_HOST=mysql
    ports:
      - 8080:80
volumes:
  postgres-data: